import os
from pathlib import Path

from sqlalchemy import create_engine, text


DB_USER = os.getenv("DB_USER", "postgres")
DB_PASSWORD = os.getenv("DB_PASSWORD", "home1213")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME", "forum_bd")

TABLES = ["users", "topics", "posts", "comments", "post_reactions"]


def quote(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def main():
    url = f"postgresql+pg8000://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
    engine = create_engine(url)
    out_path = Path(__file__).resolve().parent / "forum_bd_data.sql"
    lines = [
        "-- Data snapshot for forum_bd",
        "-- Generated by db/export_current_data.py",
        "",
        "BEGIN;",
    ]

    with engine.connect() as conn:
        for table in TABLES:
            rows = conn.execute(text(f"SELECT * FROM {table}")).mappings().all()
            if not rows:
                continue
            cols = list(rows[0].keys())
            cols_sql = ", ".join(cols)
            for row in rows:
                values_sql = ", ".join(quote(row[c]) for c in cols)
                lines.append(f"INSERT INTO {table} ({cols_sql}) VALUES ({values_sql});")

    lines.append("COMMIT;")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Exported data to {out_path}")


if __name__ == "__main__":
    main()
